- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519_github"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_github"
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/personal-projects.yml
