---
- name: Install Neovim
  shell: brew install neovim
  args:
    executable: /bin/zsh

- name: Create nvim config directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: directory
    mode: 0755

- name: Copy Neovim configuration
  copy:
    src: templates/init.lua
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/init.lua"
    mode: 0644

